[package]
name = "pobsd-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hash32 = "0.3.1"
paste = "1.0.12"
pobsd-parser = "0.2.0"
